// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjbd9ffsc9eb4opBZYAiM2W5w2E3oO7Q',
    appId: '1:214886329613:web:8517a1ed6616464dba9444',
    messagingSenderId: '214886329613',
    projectId: 'latcrud-9d46d',
    authDomain: 'latcrud-9d46d.firebaseapp.com',
    storageBucket: 'latcrud-9d46d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCHP8d6gWMDoF60S1O8eQ9nLHuYld_ZjI',
    appId: '1:214886329613:android:eaf9b8b65f023a02ba9444',
    messagingSenderId: '214886329613',
    projectId: 'latcrud-9d46d',
    storageBucket: 'latcrud-9d46d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tDIgTziOUQFOlU7AiNG4xN4GzW14Mxw',
    appId: '1:214886329613:ios:2a595c50e8649397ba9444',
    messagingSenderId: '214886329613',
    projectId: 'latcrud-9d46d',
    storageBucket: 'latcrud-9d46d.appspot.com',
    iosBundleId: 'com.example.crudDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tDIgTziOUQFOlU7AiNG4xN4GzW14Mxw',
    appId: '1:214886329613:ios:d977969f21d1eb3fba9444',
    messagingSenderId: '214886329613',
    projectId: 'latcrud-9d46d',
    storageBucket: 'latcrud-9d46d.appspot.com',
    iosBundleId: 'com.example.crudDatabase.RunnerTests',
  );
}
